name: "Build, Test, Cover"

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: true

jobs:
  build-test-cover:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --lib --examples --tests --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Coverage
      run: cargo tarpaulin --all-features --color always --count -o Lcov -t 120 -v
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
